const macroSeriesExplanations = {
  DFF: 'The Effective Federal Funds Rate is the interest rate at which banks lend reserve balances to each other overnight. It is the primary tool the Federal Reserve uses to steer monetary policy and influence borrowing costs across the economy. Rising rates typically tighten financial conditions; falling rates ease them.',
  CPIAUCSL: 'The Consumer Price Index (CPI) measures the average change in prices paid by urban consumers for a basket of goods and services. It is the most widely followed gauge of U.S. inflation. Comparing CPI trends with asset prices helps assess whether markets are pricing in inflationary or deflationary regimes.',
  UNRATE: 'The U.S. unemployment rate tracks the share of the labor force that is jobless and actively seeking work. It is a key lagging indicator of economic health. Spikes often coincide with recessions, while sustained lows can signal tight labor markets and potential wage-driven inflation.',
  DGS10: 'The 10-Year U.S. Treasury yield reflects the return on long-term government debt and serves as a benchmark for mortgage rates, corporate borrowing, and global risk pricing. Rising yields often pressure growth assets; falling yields can signal flight to safety or easing financial conditions.',
  T10Y2Y: 'The 10-Year minus 2-Year Treasury spread measures the yield curve slope. An inverted spread (short rates above long rates) has historically preceded U.S. recessions, as markets anticipate future rate cuts. It is one of the most watched recession-warning indicators.',
  T5YIE: 'The 5-Year Breakeven Inflation Rate represents market expectations for average annual inflation over the next five years, derived from Treasury yields. Rising expectations can signal concern about persistent inflation; falling expectations may indicate easing price pressures.',
  DEXUSEU: 'The Euro to U.S. Dollar exchange rate shows how many dollars one euro buys. Dollar strength or weakness affects global trade, commodity prices, and multinational earnings. FX moves often reflect relative growth, interest-rate differentials, and risk sentiment.',
  DCOILWTICO: 'West Texas Intermediate (WTI) crude oil is a benchmark for U.S. energy prices. Oil shocks can drive inflation and affect consumer spending, transportation costs, and energy-sector equities. It is closely watched as a real-economy stress indicator.',
  PPIACO: 'The Producer Price Index tracks average selling prices received by domestic producers. PPI often leads CPI because producer cost changes eventually pass through to consumers. It is useful for spotting inflation pressure earlier in the supply chain.',
  PAYEMS: 'Nonfarm payrolls measure total U.S. jobs excluding farm workers, private household employees, and nonprofit volunteers. Monthly job gains or losses are a primary read on economic momentum. Weak payroll growth often foreshadows slower consumption and risk-off market moves.',
  GDPC1: 'Real Gross Domestic Product (GDP) measures the inflation-adjusted value of all goods and services produced in the U.S. It is the broadest gauge of economic output. GDP contractions define recessions in many frameworks and strongly influence policy and asset allocation.',
  A191RL1Q225SBEA: 'Real GDP growth rate shows the quarterly percent change in inflation-adjusted economic output. Positive growth supports earnings and risk assets; negative prints signal contraction. It helps contextualize whether macro conditions are expanding or slowing.',
  M1SL: 'M1 money supply includes the most liquid forms of money: cash, checking deposits, and other immediately spendable balances. Rapid M1 expansion can reflect stimulus or liquidity injections that sometimes precede asset rallies, while contraction may signal tighter conditions.',
  M2SL: 'M2 money supply adds savings deposits, money market funds, and other near-money instruments to M1. It is a broader liquidity measure watched for links between monetary expansion, inflation, and financial asset performance.',
  FED_BALANCE: 'The Federal Reserve balance sheet (total assets) reflects the scale of Fed holdings and liquidity operations. Expansion (QE) injects reserves and often supports risk assets; contraction (QT) withdraws liquidity. Weekly WALCL data is shown in trillions of USD.',
  UMCSENT: 'The University of Michigan Consumer Sentiment Index surveys households on current and expected economic conditions. Declining sentiment can foreshadow weaker spending; improving sentiment supports consumption. It helps gauge the demand side of the economy.',
  VIXCLS: 'The CBOE Volatility Index (VIX) measures expected 30-day volatility in the S&P 500 from options prices. It is often called the "fear gauge." VIX spikes typically coincide with market stress; subdued readings suggest complacency or stable risk appetite.',
  TEDRATE: 'The TED spread is the difference between 3-month LIBOR (or equivalent) and 3-month Treasury bills. It measures perceived credit risk in the banking system. Widening spreads signal funding stress; narrowing spreads suggest improving financial stability.',
  DEXJPUS: 'The Japanese Yen to U.S. Dollar rate reflects the relative value of the yen versus the dollar. Yen moves are closely tied to global risk sentiment and carry-trade dynamics. Sharp yen strengthening often occurs during market stress.',
  DEXUSUK: 'The British Pound to U.S. Dollar exchange rate tracks sterling versus the dollar. It reflects U.K. growth, Bank of England policy, and global risk flows. Pound weakness can boost U.K. exporters but raise import inflation.',
  DEXCAUS: 'The Canadian Dollar to U.S. Dollar rate shows how many U.S. dollars one Canadian dollar buys. As a commodity-linked currency, CAD often moves with oil prices and North American growth expectations.',
  CFNAI: 'The Chicago Fed National Activity Index (CFNAI) summarizes 85 economic indicators into a single diffusion index. Values above zero suggest above-trend growth; sustained below-zero readings can signal recession risk. It is a useful composite macro pulse check.',
  USEPUINDXD: 'The Economic Policy Uncertainty Index quantifies media coverage of policy-related uncertainty. Spikes often surround elections, trade disputes, or regulatory shifts. Higher uncertainty can dampen investment and increase market volatility.',
  HOUST: 'Housing starts count new residential construction projects begun in a given period. Housing is interest-rate sensitive and a leading indicator for construction employment, lumber demand, and consumer durables spending.',
  CSUSHPINSA: 'The S&P/Case-Shiller U.S. National Home Price Index tracks residential property values. Home price trends affect household wealth, mortgage lending, and consumer confidence. Declines can signal tightening financial conditions.',
  NIKKEI225: 'The Nikkei 225 is Japan\'s leading stock market index, tracking 225 large listed companies. It reflects Japanese corporate health, yen dynamics, and Asian risk appetite. Global investors use it as a regional equity benchmark.',
  IRLTLT01DEM156N: 'The German 10-Year government bond yield is a benchmark for euro-area long-term rates. It influences European borrowing costs and is compared with U.S. yields to assess transatlantic rate differentials and growth expectations.',
  SP500: 'The S&P 500 Index tracks 500 large U.S. companies and is the primary benchmark for American equities. It reflects corporate earnings expectations, monetary policy, and global risk sentiment. Long-term trends help frame business-cycle positioning.',
  USRECD: 'The NBER-based U.S. recession indicator marks official recession periods (shaded regions). Overlaying macro or asset data against recessions helps assess how indicators behaved in past downturns and whether current readings resemble historical stress periods.',
  WALCL: 'Total assets on the Federal Reserve balance sheet (WALCL). Weekly data in millions of USD. Expansion (QE) injects system liquidity that historically supports risk assets including Bitcoin; contraction (QT) withdraws liquidity. Pair with BTC price in the Workbench to study liquidity cycles.',
  PCEPILFE: 'Core PCE is the Federal Reserve\'s preferred inflation gauge, excluding food and energy. Markets reprice rate expectations when Core PCE surprises. Useful context for risk assets when inflation is sticky versus cooling.',
  CPILFESL: 'Core CPI excludes food and energy from the consumer price basket. It is a widely watched companion to headline CPI and helps separate volatile commodity swings from underlying inflation pressure.',
  MORTGAGE30US: 'The 30-year fixed mortgage rate is a real-economy financing cost that feeds housing demand, consumer cash flow, and risk appetite. Rising mortgage rates often tighten financial conditions even when equity markets are calm.',
  DTWEXBGS: 'The Trade Weighted U.S. Dollar Index (Broad) measures the dollar against a basket of major trading partners. A strong dollar can pressure global liquidity and risk assets; a weaker dollar often coincides with easier financial conditions for crypto and emerging markets.',
};

export function getMacroSeriesExplanation(seriesId, fallback = '') {
  return macroSeriesExplanations[seriesId] || fallback;
}

export default macroSeriesExplanations;